### ISSUE TITLE
Web SDK logging everything to console

### ISSUE THREAD

**Issue by bombillazo** [GetMetaMap/metamap-demo-web-apps#6]
Hey, we want to have a flag to pass to the web sdk to turn off all logging into the console. currently the Metamap Web SDK is polluting the browser console due to the iframe logging all events:

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/44002321/219067181-31b4ee42-e34e-40df-9fbe-e082c510d099.png">

For security, performance, and development reasons, we want to disable these logs. An ideal solution would be to always disable any logs by default and to have a `debug` prop to the Metamap button in case developers need to enable and see the Metamap component logs :

```html
<metamap-button
   id="metamap-button"
   ...
   debug // this would enable those logs
/>
```

**Comment by aposnovmati** [comment]
Hello @bombillazo thanks a lot for this mention, we will take it as priority and release this month
